name: Build and Push Bun Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - develop
    paths:
      - "bun/**"
      - ".github/workflows/bun.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nodebytehosting/bun

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        tag:
          - "latest"
          - "canary"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./bun/${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:bun_${{ matrix.tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:bun_${{ matrix.tag }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
